@base_url = http://localhost:5000
@api_url = {{base_url}}/api/landing


### Get all products
# @name landing
@get_all_url = {{api_url}}
GET {{get_all_url}}




### Get a product
# @name landing_name
@get_url = {{api_url}}
GET {{get_url}}/Barsoap